# ===============================
# Global build argument
# ===============================
ARG NODE_VERSION=20

# ===============================
# Stage 1: Dependencies
# ===============================
FROM node:${NODE_VERSION}-alpine AS deps
WORKDIR /app

COPY package*.json ./
RUN npm ci


# ===============================
# Stage 2: Test
# ===============================
FROM node:${NODE_VERSION}-alpine AS test
WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Runtime env 
ENV SALT=""

RUN npm test


# ===============================
# Stage 3: Dev runtime
# ===============================
FROM node:${NODE_VERSION}-alpine AS dev
WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Runtime environment variables
ENV NODE_ENV=development
ENV SALT=""

EXPOSE 8080
CMD ["npm", "run", "dev"]
